### ISSUE TITLE
[Bug report] Missing Page : default-theme

### ISSUE THREAD

**Issue by RowanWang6** [vuepress/docs#12]
### Description

https://v2.vuepress.vuejs.org/reference/default-theme/config.html
It's 404 now.
The link I click: 
<img width="1231" alt="image" src="https://github.com/vuepress/docs/assets/87600024/4c11887b-b0ef-49bf-bda2-1580a4f7e088">

**Comment by Mister-Hope** [comment]
Thanks for reporting
