### ISSUE TITLE
[Bug report] Element is missing end tag.

### ISSUE THREAD

**Issue by web1992** [vuepress/docs#13]
### Description

```md
# Guide

This is guide page.

<div>

```

当我使用 div 标签，没有闭合标签结尾的时候，就出现下面的错误。

![image](https://github.com/vuepress/docs/assets/6828647/44553742-2359-4c9f-ac34-6f9c9240852c)

这种情况怎么解决？比如Java 中的泛型 ` List<String>` 也会遇到这样问题。
问题的原因是 md 文件被解析成了vue 文件，而vue 文件中 template是不能存在没有闭合的 html 标签的。

目前可以使用下面的方式解决。有其他更好的方式吗?
```md
`<div>`
```

**Comment by Mister-Hope** [comment]
why do you think it's an issue?

Write some standard markdown plz. 

List\<string>

```md
List\<string>
```
