### ISSUE TITLE
print preview effect problem?

### ISSUE THREAD

**Issue by Jairwin-L** [vuepress/docs#15]
### Description

the print preview effects of the two versions are different. the v2 version should be the same as v1, right?
v2.x.
![image](https://github.com/vuepress/docs/assets/32570960/b5b20286-61c7-4fb2-811e-5f44a6100d70)
![image](https://github.com/vuepress/docs/assets/32570960/4a8ace86-144e-4bbc-877a-319b0868ea2d)
v1.x.
![image](https://github.com/vuepress/docs/assets/32570960/501b32fa-c0f5-4a00-95d9-f9f8635edc24)
![image](https://github.com/vuepress/docs/assets/32570960/2b8f1d8c-1c0e-4b74-87bd-273b80387bca)

**Comment by Mister-Hope** [comment]
Why do you think expanding the link could be bad? At least it gives reference for what the link is pointing.

You could definitely disable this via css.

**Comment by Jairwin-L** [comment]
A scenario I have encountered at present is that if you make a resume, after printing it out, the redundant links displayed will make the entire page take up a lot of space; at the same time, the readability is not high.
Furthermore, why is there such a difference between the two versions?

**Comment by Mister-Hope** [comment]
If a page is a good printable one, anyone should not expect to see lots of links in it. For example, a normal blog post should mainly contain plain text, instead of adding lots of reference in lines.

Besides, we are only printing external links, which is probably not attachable even if you print all pages, so we think that it's better to declare their address.

You can easily hide your website links with CSS:


```css
a {
  @media print {
    &[href^="http://"],
    &[href^="https://"]
    {
      &::after {
        content: ''!important;
      }
    }
  }
}
```

Do you still need any further discussion?

**Comment by Jairwin-L** [comment]
Of course, what you are talking about is also from one aspect, and I should be able to understand it.
My main points here are: there are external links because they can be accessed online, and they are printable so that readers can directly print the original content. Even if there are links, they are displayed in text form. As you said, it can be solved through CSS. I also Agree with this.
Because I saw that v2 is different from v1, I suddenly wanted to know more about this aspect. Of course, there may be a blind spot in my knowledge in this aspect.
