### ISSUE TITLE
[Bug report] v2: broken search result links

### ISSUE THREAD

**Issue by olets** [vuepress/docs#20]
### Description

I'm using the docs for the first time in months, and am hitting many broken URLs in search results.

For example, when searching for "container", the top ten results are at these nonexistent pages:

https://vuepress.github.io/reference/plugin/container.html
https://vuepress.github.io/reference/default-theme/markdown.html
https://vuepress.github.io/reference/default-theme/config.html
https://vuepress.github.io/reference/default-theme/components.html

In those cases, the pages are now on https://ecosystem.vuejs.press/.

Based on those cases, maybe the solution is to change or redirect all `vuepress.github.io/reference/default-theme/*` URLs to `ecosystem.vuejs.press/themes/default/*`, and all `vuepress.github.io/reference/plugin/*` to `ecosystem.vuejs.press/plugins/*`. I haven't gone through to see if any slugs don't fit the pattern, or to see what other sections have moved.

**Comment by Mister-Hope** [comment]
algolia recraw will be blocked if the records reduce up to a limit.

so.I guess this is the situation.

**Comment by meteorlxy** [comment]
Just force refreshed the index

Thanks for reporting! ❤️
