### ISSUE TITLE
[Bug report] two pnpm option on 'Getting Started' section

### ISSUE THREAD

**Issue by LoongArum** [vuepress/docs#33]
### Description

The raw markdown file is correct but both Chinese and English page display wrong.
![image](https://github.com/user-attachments/assets/673d0737-f811-429d-a287-34a1983f4ebf)

**Comment by LoongArum** [comment]
raw markdown section: 
- Install VuePress

<CodeGroup>
  <CodeGroupItem title="pnpm" active>

```bash
# install vuepress and vue
pnpm add -D vuepress@next vue
# install bundler and theme
pnpm add -D @vuepress/bundler-vite@next @vuepress/theme-default@next
```

  </CodeGroupItem>

  <CodeGroupItem title="yarn">

```bash
# install vuepress
yarn add -D vuepress@next
# install bundler and theme
yarn add -D @vuepress/bundler-vite@next @vuepress/theme-default@next
```

  </CodeGroupItem>

  <CodeGroupItem title="npm">

```bash
# install vuepress
npm install -D vuepress@next
# install bundler and theme
npm install -D @vuepress/bundler-vite@next @vuepress/theme-default@next
```

  </CodeGroupItem>
</CodeGroup>

**Comment by LoongArum** [comment]
```- Install VuePress

<CodeGroup>
  <CodeGroupItem title="pnpm" active>

```bash
# install vuepress and vue
pnpm add -D vuepress@next vue
# install bundler and theme
pnpm add -D @vuepress/bundler-vite@next @vuepress/theme-default@next
```

  </CodeGroupItem>

  <CodeGroupItem title="yarn">

```bash
# install vuepress
yarn add -D vuepress@next
# install bundler and theme
yarn add -D @vuepress/bundler-vite@next @vuepress/theme-default@next
```

  </CodeGroupItem>

  <CodeGroupItem title="npm">

```bash
# install vuepress
npm install -D vuepress@next
# install bundler and theme
npm install -D @vuepress/bundler-vite@next @vuepress/theme-default@next
```

  </CodeGroupItem>
</CodeGroup>
```

**Comment by Mister-Hope** [comment]
https://github.com/vuepress/docs/commit/8c2c25a88bb1120cfef877ad7516fe23e0b14c66

**Comment by LoongArum** [comment]
> [8c2c25a](https://github.com/vuepress/docs/commit/8c2c25a88bb1120cfef877ad7516fe23e0b14c66)
大佬，你是怎么有空边研究物理还研究编程的:)
