### ISSUE TITLE
[Bug report] 文档中部署部分描述过期docs->src

### ISSUE THREAD

**Issue by W1ndys** [vuepress/docs#37]
### Description

https://vuejs.press/zh/guide/deployment.html
文档中描述的Markdown存放目录是docs
实测初始化的存放目录是src
![image](https://github.com/user-attachments/assets/0100fc27-bdc7-45aa-a6f8-4bb3ff911f7c)
![image](https://github.com/user-attachments/assets/e88ffb59-fdc0-4573-8d51-83004337b1f9)

**Comment by meteorlxy** [comment]
@Mister-Hope I think it's better to update the create package and add test cases

**Comment by Mister-Hope** [comment]
Nope, I don't think this report is valid:

![image](https://github.com/user-attachments/assets/5c289014-0cd0-4e53-b145-607fe00cb131)

**Comment by W1ndys** [comment]
@Mister-Hope 
I understand. Can it be understood that the original version of vuepress is `docs`, but your theme is `src`?

**Comment by Mister-Hope** [comment]
This is because my theme supports both documentation sites and blog site. It is strange that a blog use docs as folder.
