### ISSUE TITLE
[Bug report] 

### ISSUE THREAD

**Issue by aoleou** [vuepress/docs#8]
### Description
Hi, thanks for create this project, and I find a may be bug in below, plz help me to resolve this.
clone `https://github.com/vuepress/docs.git`, and delete the `pnpm-lock.yaml` file, and run the command `pnpm install && pnpm run docs:dev`, it will have the warn:
```text
[Vue warn]: inject() can only be used inside setup() or functional components.
[Vue warn]: Unhandled error during execution of scheduler flush. This is likely a Vue internals bug. Please open an issue at https://github.com/vuejs/core .
[Vue Router warn]: uncaught error during route navigation:
```
and 
error: 
```text
vue-router.js?v=be8b02e0:2504 TypeError: Cannot read properties of undefined (reading 'resolve')
```
in the console of chrome, and there is no sidebar in the web
reproduction: https://github.com/aoleou/docs2.git

**Comment by Mister-Hope** [comment]
revert to vue3.3 plz as a workaround

**Comment by Mister-Hope** [comment]
Nope, 3.3.13, without the ^

**Comment by Mister-Hope** [comment]
@meteorlxy we need to continue rolling out a new version compatible with vue3.4. Any progress with the ts bug?

**Comment by aoleou** [comment]
Amazing! It seem like the problem is solved.

**Comment by Mister-Hope** [comment]
Closed with https://github.com/vuepress/ecosystem/commit/6d78f5d0972c023027f44ae891833657f1da0adb
